# 記事リポジトリの .github/workflows/trigger-deploy.yml
name: Trigger Parent Build
on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to Parent Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }} # Personal Access Tokenが必要
          repository: khimoo/portfolio-page
          event-type: content-updated
